### ISSUE TITLE
orik has a dependency on pyc4?

### ISSUE THREAD

**Issue by dotnwat** [KDahlgren/orik#2]
it looks like orik contains its own c4 python wrapper. would it be reasonable to have orik depend on pyc4?

**Comment by KDahlgren** [comment]
It would be reasonable to have orik depend upon pyc4, given how the C4Wrapper is currently implemented in pyc4; it’s essentially the same file and possesses all the logic necessary to orchestrate the proper introduction of clock facts into the c4 evaluator. That happened purely as a consequence of me essentially ripping out the c4 wrapper from pyldfi both when constructing pyc4 and constructing orik. 

However, since pyc4 is intended to be a purely python interface over c4, the current C4Wrapper script contains a lot of dead code. I just haven’t cleaned it up yet. Also, strictly speaking, given the goals of pyc4, the clock introduction logic is not necessary. The extra clock logic only makes sense when running overlog programs derived from dedalus programs. 

Accordingly, at the moment, I’m leaning toward having orik be as stand-alone as possible, rather than introducing a reliance on pyc4, since the clock management logic is so critical to the correctness of dedalus program evaluations.
